Repository ornladios/ADIOS2, pull requests merged in 2020-05, with the labels that each got.

#1996 Add CMake module to detect float representation
  cmake/CheckTypeRepresentation.cmake
  cmake/CheckTypeRepresentationCompile.c.in
  cmake/CheckTypeRepresentationCompile.f.in
  cmake/CheckTypeRepresentationRun.c.in
  cmake/DetectOptions.cmake
  cmake/Internal/FloatRepresentationTable.cmake
Labels: area: build, don't merge yet, status: work-in-progress

#2207 Replace message(CHECK_* ...) with message(STATUS ...)
  cmake/CheckTypeRepresentation.cmake
Labels: area: build

#2209 Use WITH_SOABI argument in Python_add_library()
  bindings/Python/CMakeLists.txt
Labels: api: Python, area: build

#2216 Add install components
  CMakeLists.txt
  bindings/C/CMakeLists.txt
  bindings/CXX11/CMakeLists.txt
  bindings/Fortran/CMakeLists.txt
  bindings/Python/CMakeLists.txt
  cmake/adios2-config-common.cmake.in
  cmake/install/packaging/CMakeLists.txt
  cmake/install/post/CMakeLists.txt
  cmake/install/pre/CMakeLists.txt
  source/adios2/CMakeLists.txt
  source/adios2/toolkit/sst/CMakeLists.txt
  source/adios2/toolkit/sst/util/CMakeLists.txt
  source/utils/CMakeLists.txt
  source/utils/adios_iotest/CMakeLists.txt
  source/utils/bp4dbg/CMakeLists.txt
  thirdparty/EVPath/CMakeLists.txt
  thirdparty/atl/CMakeLists.txt
  thirdparty/dill/CMakeLists.txt
  thirdparty/enet/CMakeLists.txt
  thirdparty/ffs/CMakeLists.txt
Labels: area: build

#2226 DRC Fix (replaces #2222)
  source/adios2/toolkit/sst/dp/rdma_dp.c
Labels: area: staging

#2225 Handle pending releases when closing writer
  source/adios2/toolkit/sst/cp/cp_writer.c
Labels: area: staging, don't merge yet

#2208 Add library suffix option
  CMakeLists.txt
  bindings/C/CMakeLists.txt
  bindings/CXX11/CMakeLists.txt
  bindings/Fortran/CMakeLists.txt
  bindings/Python/CMakeLists.txt
  bindings/Python/__init__.py
  bindings/Python/__init__.py.in
  bindings/Python/py11glue.cpp
  cmake/install/post/generate-adios2-config.sh.in
  scripts/ci/cmake/ci-debian-sid-openmpi.cmake
  scripts/ci/cmake/ci-debian-sid.cmake
  source/adios2/CMakeLists.txt
  source/adios2/toolkit/sst/CMakeLists.txt
  source/adios2/toolkit/sst/util/CMakeLists.txt
  source/utils/CMakeLists.txt
  source/utils/adios_iotest/CMakeLists.txt
  testing/install/C/Makefile
  testing/install/CMakeLists.txt
  testing/install/CXX11/Makefile
  testing/install/Fortran/Makefile
  testing/install/run_make.cmake
  thirdparty/EVPath/CMakeLists.txt
  thirdparty/atl/CMakeLists.txt
  thirdparty/dill/CMakeLists.txt
  thirdparty/enet/CMakeLists.txt
  thirdparty/ffs/CMakeLists.txt
Labels: area: build

#2266 Release lock during RDMADestroyWriter
  source/adios2/toolkit/sst/dp/rdma_dp.c
Labels: bug

#2272 Update install directories to more closely reflect Debian package
  scripts/ci/cmake/ci-debian-sid-openmpi.cmake
  scripts/ci/cmake/ci-debian-sid.cmake
  scripts/ci/images/debian-sid/Dockerfile
Labels: area: build
