Repository ornladios/ADIOS2, pull requests merged in 2023-09, with the labels that each got.

#3789 gha,ci: update checkout to v4
  .github/workflows/everything.yml
Labels: backport:release

#3799 yaml-cpp: support 0.8.0 version
  thirdparty/CMakeLists.txt
Labels: area: build, backport:release

#3804 Set AWS version requirement to 1.10.15 and also turn it OFF by defaul…
  CMakeLists.txt
  cmake/DetectOptions.cmake
Labels: backport:master
