Repository ornladios/ADIOS2, pull requests merged in 2024-01, with the labels that each got.

#3979 python,cmake: update version script to support rc
  scripts/ci/gh-actions/config/adios-version.cmake
Labels: backport:release

#3980 Fix the C example stepping and reading data. Simplify code for shape/…
  examples/basics/globalArray1D/decomp.c
  examples/basics/globalArray1D/decomp.h
  examples/basics/globalArray1D/globalArray1DRead.c
  examples/basics/globalArray1D/globalArray1DWrite.F90
  examples/basics/globalArray1D/globalArray1DWrite.c
Labels: backport:master

#3982 ASAN cleanup
  CTestConfig.cmake
  scripts/ci/cmake/adios-asan.supp
  source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
  source/adios2/toolkit/format/bp5/BP5Serializer.cpp
  source/adios2/toolkit/remote/Remote.cpp
  source/adios2/toolkit/remote/Remote.h
  source/adios2/toolkit/remote/remote_common.h
  source/adios2/toolkit/sst/cp/cp_reader.c
Labels: sustainability

#3993 Fix read request length on BP5 Local arrays with operators (backport to release 2.10)
  source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
Labels: sustainability

#3994 Fix 1: bpls handle when BP5 throws logic error on minmax for unsuppor…
  examples/basics/values/values.F90
  examples/basics/values/valuesWrite.cpp
  source/utils/bpls/bpls.cpp
Labels: backport:master, sustainability
